<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/mangosweat/3/mutlishooter/static/models/Bullet.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/Bullet.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['9x19mm_Glock19002_Cube001-Mesh'].geometry}
      material={gltf.materials['BulletCasing.001']}
    />
    <T.Mesh
      geometry={gltf.nodes['9x19mm_Glock19002_Cube001-Mesh_1'].geometry}
      material={gltf.materials['BulletTip.001']}
    />
    <T.Mesh
      geometry={gltf.nodes['9x19mm_Glock19002_Cube001-Mesh_2'].geometry}
      material={gltf.materials['BulletCasing2.001']}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
