<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/mangosweat/3/mutlishooter/static/models/Tank.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/Tank.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={112.29}>
      <T.Mesh geometry={gltf.nodes.Tank_1.geometry} material={gltf.materials.Tank_Main} />
      <T.Mesh geometry={gltf.nodes.Tank_2.geometry} material={gltf.materials.Tank_Main2} />
      <T.Mesh geometry={gltf.nodes.Tank_3.geometry} material={gltf.materials.Grey} />
      <T.Mesh geometry={gltf.nodes.Tank_4.geometry} material={gltf.materials['Black.001']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
